name: 'Security requirement analysis with ARQAN and RQCODE'
description: 'Issues mapping to security recommendations from STIG database for Windows 10. The action provides recommendations and ready-to-use tests from RQCODE.'
inputs:
  rqcode-token:
    description: 'The GitHub token of the user to create GitHub Issue in RQCODE repository in case of absence of the test.'
    required: false
  label:
    description: 'Label of security requirement'
    required: false
    default: 'security'
  stigs-comment:
    description: 'Enable STIGs suggestion through issue commenting'
    required: false
    default: 'true'
  search-tests:
    description: 'Enable search for tests in RQCODE repository'
    required: false
    default: 'true'
  create-issues:
    description: 'Enable issue creation in RQCODE repository'
    required: false
    default: 'false'
  token:
    description: 'The GitHub token to use.'
    required: false
    default: ${{ github.token }}
  platform:
    description: 'Platform for STIGs'
    required: false
    default: 'windows_10'
  username:
    description: 'ARQAN username'
    required: true
  password:
    description: 'ARQAN password'
    required: true
  limit:
    description: 'Max number of suggested STIGs'
    required: false
    default: '5'
  api_url:
    description: 'Recommendation service API url'
    required: false
    default: 'https://arqan.softeam-rd.eu/api'
runs:
  using: 'node16'
  main: 'dist/index.js'
