name: ARQAN map issue

on: 
  issues:
    types: 
      - labeled

jobs:
  stig:
    runs-on: ubuntu-latest
    name: Add label to Issue if it is secure
    steps:
      - uses: actions/checkout@v3
      - uses: ./ # load and run local action
        if: github.event.label.name == 'arqan'
        name: Label an issue and provide recommendtations
        with:
#          rqcode-token: ${{ secrets.RQCODE_TOKEN }}
          platform: windows_10
          username: ${{ secrets.ARQAN_USER }}
          password: ${{ secrets.ARQAN_PASS }}
          create-issues: 'false'
